### ISSUE TITLE
艺术殿堂 - （完）电棍：♿波西唢呐狂想曲♿

### ISSUE THREAD

**Issue by CwavGuy** [HanaYabuki/otto-hzys#1]
Ccvbn -（完）电棍：♿波西唢呐狂想曲♿
![bxsnkxq](https://user-images.githubusercontent.com/25190647/218139857-eb2e80d9-1b45-49dc-a70e-558343e65455.jpg)
[Ccvbn -（完）电棍：♿波西唢呐狂想曲♿.zip](https://github.com/HanaYabuki/otto-hzys/files/10709258/Ccvbn.-.zip)

爱谁不是爱，不如让我阐述阿姨和申鹤的梦。
Best Regards.

**Comment by HanaYabuki** [comment]
整了，谢谢
