### ISSUE TITLE
声像严重偏置

### ISSUE THREAD

**Issue by AkutaZehy** [HanaYabuki/otto-hzys#10]
看着好玩就随便Generate了一个，然后发现声像偏置极其严重。

文本：

不是我就不明白了看你爹操作这波

群友，生活费够吗，够的话转我点，不要说我不要脸，将心比心，你穿的鞋都是谁买的？是，都是你自己买的，但你平时吃的喝的都是谁买的？我承认也是你自己买的，但是你有没有考虑过你给自己买这么多东西是不是太自私了?为什么不给我买呢？就因为我们素不相识吗？

奥利安费 all in

![图片](https://github.com/HanaYabuki/otto-hzys/assets/42381419/ba20eec4-822a-4f56-b075-72559fe805a6)

![QQ截图20231130130428](https://github.com/HanaYabuki/otto-hzys/assets/42381419/d8fcaa3d-51ab-4758-bacf-5d5bd5064188)

OS：不过看上去这个仓库好像闲置有一段时间了w

**Comment by HanaYabuki** [comment]
我本来处理这个问题了，之前有个啥懒子给我wav全换成mp3之后就这样了，我素材全给我弄乱了不说声像也给搞坏了。后来我也没改，这几天也没啥时间了。你会弄就自己弄了提个pr得了。

**Comment by AkutaZehy** [comment]
光顾着看commit去了没看pr（）
好那Close了有空看看
