### ISSUE TITLE
请问作者使用教程

### ISSUE THREAD

**Issue by LG1413** [HanaYabuki/otto-hzys#2]
兄啊,你这个怎么用啊,点击public里的index.html是一片空白啊
![Snipaste_2023-04-12_08-42-02](https://user-images.githubusercontent.com/79795225/231318301-d755a8b3-5850-43c1-8fee-0524f8146130.png)

**Comment by HanaYabuki** [comment]
![image](https://user-images.githubusercontent.com/58248573/231327168-1388e971-7dfd-4e45-bb96-4d975a891a4e.png)
确实不太显眼，一会儿我去readme里补一个

**Comment by PencilCore** [comment]
这玩意太搞了，接入qq机器人增加点效果

**Comment by LG1413** [comment]
其实我用了另一个人的工具了，它用浏览器和python完成了

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年4月30日 10:20
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [HanaYabuki/otto-hzys] 请问作者使用教程 (Issue #2)


这玩意太搞了，接入qq机器人增加点效果

―

**Comment by shanniruo-tytx** [comment]
哇袄

**Comment by LG1413** [comment]
哈比下的

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年5月10日 14:17
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [HanaYabuki/otto-hzys] 请问作者使用教程 (Issue #2)


哇袄

―
