### ISSUE TITLE
哥求你了怎么进行本地部署

### ISSUE THREAD

**Issue by ZXL-Q** [HanaYabuki/otto-hzys#6]
如标题,我想试试拿自己电脑进行十分甚至是九分的使用 但是网比otto还要答辩 求求你了哥

**Comment by HanaYabuki** [comment]
Vue3项目怎么部署这个就怎么部署呀，你那边怎么回事，细说我帮你看看

**Comment by Stallion-X** [comment]
先装好Node.js和npm环境
git clone以后直接在根目录下面`npm i`
最后`npm run serve`启动
