### ISSUE TITLE
原声大碟

### ISSUE THREAD

**Issue by linland-h** [HanaYabuki/otto-hzys#8]
能不能在原声大碟里加入 "我艹死你的🐎" 的适配，求你了，我什么都不会做的

**Comment by HanaYabuki** [comment]
自己写代码自己提Pr，我看到了就会合

**Comment by linland-h** [comment]
> 自己写代码自己提Pr，我看到了就会合

好哥哥，pr提了

**Comment by HanaYabuki** [comment]
给你合了，现在代码乱的一坨屎我也不知道怎么改了，前面人给我写出一堆坑来，我也不想维护了就这样糊弄糊弄来吧
